// Colors and names for your borehole types (matches AGS HOLE_TYPE values in our data)
export const agsHoleTypeConfig = {
  SCP: {
    color: "#e31a1c",
    name: "Standard Penetration Test",
  },
  "CP+RO+RC": {
    color: "#1f78b4",
    name: "CPT + Rotary Open + Rotary Cored",
  },
  "CP+RC+RO": {
    color: "#1f78b4",
    name: "CPT + Rotary Cored + Rotary Open",
  },
  "CP+RO": {
    color: "#33a02c",
    name: "CPT + Rotary Open",
  },
  "RO+CP": {
    color: "#33a02c",
    name: "Rotary Open + CPT",
  },
  VC: { color: "#ff7f0e", name: "Vibro Core" },
  RC: { color: "#984ea3", name: "Rotary Cored" },
  Grab: { color: "#ff7f00", name: "Grab Sample" },
  RCG: { color: "#a65628", name: "Rotary Cored + Grab" },
  "IP+W+RCG": {
    color: "#f781bf",
    name: "In-situ Piezometer + Water + Rotary Cored + Grab",
  },
  "IP+W": { color: "#999999", name: "In-situ Piezometer + Water" },
  TP: { color: "#4daf4a", name: "Trial Pit" },
};

// Geological configuration with colors and descriptions
export const geologicalConfig = {
  BLANK: { color: "#cccccc", description: "BLANK" },
  CLAYZSB: { color: "#7a4a0a", description: "Sandy silty CLAY with shells" },
  SANDZB: { color: "#e76f51", description: "Silty SAND with shell fragments" },
  CLAYZSO: { color: "#bf7330", description: "Sandy silty CLAY with organics." },
  SILTS: { color: "#ffffbf", description: "Sandy SILT" },
  CLAYS: { color: "#a0621a", description: "Sandy CLAY" },
  SANDZ: { color: "#fdae61", description: "Silty SAND" },
  SANDZG: { color: "#2a9d8f", description: "Silty SAND with gravels" },
  CLAYSB: { color: "#a0621a", description: "Sandy CLAY with shells." },
  SANDCZGB: {
    color: "#2a9d8f",
    description: "Silty, clayey SAND with gravel and shells",
  },
  SILTSB: { color: "#ffffbf", description: "Sandy SILT with shell." },
  CLAYSO: { color: "#a0621a", description: "Sandy CLAY with organic matter." },
  SILTSO: { color: "#ffffbf", description: "Sandy SILT with organics." },
  SANDC: { color: "#f4a261", description: "Clayey SAND" },
  CLAYZSG: { color: "#5a3a0a", description: "Sandy silty CLAY with gravel" },
  SILTCSG: { color: "#e0e09f", description: "Sandy Clayey SILT with gravel" },
  SANDCG: { color: "#f4a261", description: "Clayey SAND with gravel" },
  GRANITE: {
    color: "#e6a0c4",
    description: "Granite, Coarse-grained Acid Igneous Rock",
  },
  GRAV: { color: "#999999", description: "GRAVEL" },
  SILTCS: { color: "#f0f0af", description: "Sandy Clayey SILT" },
  SILTSG: { color: "#ffffbf", description: "Gravelly sandy  SILT." },
  SANDZO: { color: "#fdae61", description: "Silty SAND with organics." },
  CLAYZ: { color: "#8c510a", description: "Silty CLAY" },
  SANDZGB: {
    color: "#2a9d8f",
    description: "Silty gravelly SAND with shells.",
  },
  SANDCB: { color: "#f4a261", description: "Clayey SAND with shell fragments" },
  CLAYZS: { color: "#a0621a", description: "Sandy silty CLAY" },
  CLAYZSGB: {
    color: "#5a3a0a",
    description: "Sandy silty CLAY with gravel and shells",
  },
  SILTSGK: {
    color: "#ffffbf",
    description: "Sandy SILT with gavel and cobbles.",
  },
  SANDCZG: { color: "#2a9d8f", description: "Silty, clayey SAND with gravel" },
  SILTCB: { color: "#f0f0af", description: "Clayey SILT wth shells" },
  SILTCSB: { color: "#f0f0af", description: "Sandy Clayey SILT with shells" },
  SILTC: { color: "#f0f0af", description: "Clayey SILT" },
  SANDCZB: { color: "#e76f51", description: "Silty, clayey SAND with shells" },
  SANDCZ: { color: "#f4a261", description: "Silty, clayey SAND" },
  SANDB: { color: "#fdae61", description: "SAND with shell" },
  SAND: { color: "#fdae61", description: "SAND" },
  GRAVCZS: { color: "#999999", description: "Sandy silty clayey GRAVEL" },
  CLAYZO: { color: "#bf7330", description: "Silty CLAY with organic matter" },
  CLAYZB: { color: "#8c510a", description: "Silty CLAY with shells" },
  SANDG: { color: "#2a9d8f", description: "Gravelly SAND" },
  FILL: {
    color: "#654321",
    description: "Artificial Fill; includes landfill, rock fill, masonry wall",
  },
  CLAYZSGK: {
    color: "#5a3a0a",
    description: "Sandy silty CLAY with gravel and cobbles.",
  },
  SANDCZO: {
    color: "#e9c46a",
    description: "Clayey silty SAND with organic matter",
  },
  BASALT: { color: "#e6a0c4", description: "Basalt" },
  CBBL: { color: "#999999", description: "Cobbles" },
  CLAYZG: { color: "#5a3a0a", description: "Silty CLAY with gravel" },
  GRAVCBBL: { color: "#999999", description: "GRAVEL and COBBLES." },
  GRAVCZ: { color: "#999999", description: "Silty clayey GRAVEL" },
  GRAVS: { color: "#999999", description: "Sandy GRAVEL" },
  GRAVZS: { color: "#888888", description: "Silty Sandy GRAVEL" },
  SANDGB: { color: "#2a9d8f", description: "SAND with gravel and shells." },
  ASPHALT: { color: "#654321", description: "Asphalt" },
  CONCRETE: { color: "#cccccc", description: "CONCRETE" },
  SILTCSO: {
    color: "#f0f0af",
    description: "Sandy clayey SILT with organics.",
  },
  SURFACE: {
    color: "#cccccc",
    description:
      "Artificial Surfacing - Masonry, stone/brick pitching, Shotcrete/chunam surface, etc.",
  },
  CLAYSG: { color: "#a0621a", description: "Sandy CLAY with gravel" },
  WASHING: { color: "#cccccc", description: "Wash Boring" },
  SANDZGK: {
    color: "#2a9d8f",
    description: "Silty SAND with gravel and cobbles.",
  },
  SANDCGO: {
    color: "#f4a261",
    description: "Clayey SAND with gravel and organic matter.",
  },
  SANDGK: { color: "#2a9d8f", description: "SAND with gravel and cobbles." },
  PEGMTITE: { color: "#e6a0c4", description: "Pegmatite" },
  CLAYO: { color: "#8c510a", description: "CLAY with organic matter." },
  CLAYB: { color: "#8c510a", description: "Shelly CLAY" },
  SILTCO: { color: "#f0f0af", description: "Clayey SILT with organics." },
  SILTCSGO: {
    color: "#e0e09f",
    description: "Sandy clayey SILT with gravel and organic matter",
  },
  CBBLG: { color: "#999999", description: "COBBLES with gravel." },
  CBBLS: { color: "#999999", description: "COBBLES with sand." },
  CBBLSG: { color: "#999999", description: "COBBLES with sand and gravel." },
  CBBLZSG: {
    color: "#999999",
    description: "COBBLES with silty sandy gravel.",
  },
  CLAY: { color: "#8c510a", description: "CLAY" },
  CLAYG: { color: "#8c510a", description: "Gravelly CLAY" },
  GRAVSK: { color: "#999999", description: "Sandy GRAVEL with cobbles." },
  GRAVZSK: {
    color: "#888888",
    description: "Silty sandy GRAVEL with cobbles.",
  },
  SILT: { color: "#ffffbf", description: "SILT." },
  SILTG: { color: "#ffffbf", description: "Gravelly SILT." },
  SANDCZK: { color: "#f4a261", description: "Silty clayey SAND with cobbles." },
  CBBLCZSG: {
    color: "#999999",
    description: "COBBLES & BOULDERS with silty, sandy gravel",
  },
};